const message = {
  registered: 'Registered successfully',
  under_process: 'Request under process',
  permission_denied: 'Permission denied',
  login_success: 'Login successfully',
  success: 'All users data',
  server_error: 'Internal server error',
  updated: 'User data updated successfully',
  user_data: 'User data',
  user_delete: 'User deleted successfully',
  request_pending: 'Request pending for approval',
  already_exists: 'Email or username already exists',
  not_exists: 'user not exists',
  request_approved: 'Your request has been approved',
  wrong_pwd: 'wrong password',
  invalid_credentials: 'Invalid credentials',
  logout: 'You have been Logged Out',
  req_not_available: 'No requests available',
  all_requests: 'All requests',
  request_decline: 'your request has been declined',
  request_cancelled: 'Request cancelled successfully',
  request_generated: 'request generated successfully',
  blood_not_available: 'requested blood not available',
  blood_bank_added: 'blood bank added successfully',
  blood_bank_already_exists: 'do not have permission to add blood bank or blood bank already added by you!',
  all_blood_banks: 'All Blood banks data',
  inventory_added: 'blood Inventory added successfully',
  already_added_inventory:'already added inventory',
  prices_added: 'blood prices added successfully',
  already_added_prices: 'already added prices',
  inventory_updated: 'inventory updated successfully',
  prices_updated:'blood price updated successfully'
};
module.exports = message;
